gl_zeist_admin:
    resource: "@GLZeistProgrammaBundle/Controller/Admin"
    type:     annotation
    prefix:   /admin
    
gl_zeist_thema:
    resource: "@GLZeistProgrammaBundle/Controller/App/ThemaController.php"
    type:     annotation    
    
gl_zeist_hoofdstuk:
    resource: "@GLZeistProgrammaBundle/Controller/App/HoofdstukController.php"
    type:     annotation    
    
gl_zeist_kandidaat:
    resource: "@GLZeistProgrammaBundle/Controller/App/KandidaatController.php"
    type:     annotation    

gl_zeist_wijk:
    resource: "@GLZeistProgrammaBundle/Controller/App/WijkController.php"
    type:     annotation    
        
gl_zeist:
    resource: "@GLZeistProgrammaBundle/Controller/App/DefaultController.php"
    type:     annotation
    
gl_zeist_published:
    resource: "@GLZeistProgrammaBundle/Controller/App/PublishedItemController.php"
    type:     annotation    
    
gl_zeist_rss:
    resource: "@GLZeistProgrammaBundle/Controller/App/RSSController.php"
    type:     annotation    
  

admin_login_check:
    pattern: /admin/login_check
    

# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
