gl_zeist_admin:
    resource: "@GLZeistProgrammaBundle/Controller/Admin"
    type:     annotation
    prefix:   /admin
    
gl_zeist:
    resource: "@GLZeistProgrammaBundle/Controller/App"
    type:     annotation
  

admin_login_check:
    pattern: /admin/login_check
    

# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
