jms_security_extra:
    secure_all_services: false
    expressions: true

security:
        
    encoders:
        GLZeist\Bundle\ProgrammaBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1        

    role_hierarchy:
        ROLE_MODERATOR:   ROLE_USER
        ROLE_ADMIN:       [ROLE_USER,ROLE_MODERATOR]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_MODERATOR, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        editors:
            entity: { class: GLZeistProgrammaBundle:User, property: username }

    firewalls:
      
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/admin/
            security: true
            anonymous: ~
            remember_me:
                key: %secret%
                lifetime: 31536000
                path: ~
                domain: ~            
            form_login:
                check_path: /admin/login_check
                login_path: /admin/login
                default_target_path: /admin/item
            logout:
                path:   /admin/logout
                target: /admin/login
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/item/publish, roles: ROLE_MODERATOR }
        - { path: ^/admin/item, roles: ROLE_USER }
        - { path: ^/admin/user, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_MODERATOR }
        
        
        
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #
        # You must uncomment the two following rules to restrict access to paths
        # starting with the /_internal prefix to only localhost
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
        #- { path: ^/_internal/secure, roles: ROLE_NO_ACCESS }
